#!/bin/sh

#TODO: Feature request: vcli --quiet option
#TODO: Feature request: vcli return id option
#TODO: Add support for multiple tags
#TODO: Add support for multiple paths in VCL_PATH
#TODO: Add support for shared deployments
#TODO: Add support for automatically detecting VCL includes
#TODO: Add support for routing rules
#TODO: Add support for staged deployments
#TODO: Add support for drafts and rollbacks
#TODO: Add test suite

usage() {
	test $# -eq 1 &&
	printf 'Error: %s.\n\n' "$1"

	cat <<-EOF
	Usage: $SCRIPT -g <VCL Group> -t <tags> -f <Main VCL> -p <VCL Path>
	       $SCRIPT -h

	Connect to Varnish Controller and (re)deploy a VCL Group. This script
	relies on vcli, so please ensure that varnish-controller-cli is
	installed.

	Available options:
	-g           : Name of the VCL Group
	-t           : Deployment tags
	-f           : Name of the Main VCL
	-p           : Path to VCL directory
	-h           : show this help and exit

	EOF
	exit $#
}

fail() {
	echo "$*\n" >&2
	exit 1
}

awk_id() {
	awk -F ',' 'BEGIN { id = 0 } { if (NR == 2) {id=$1; exit} } END { print id }'
}

vcli_run_quiet() {
	(vcli "$@" 2> /dev/null --csv) | awk_id
}

vcli_run() {
	(vcli "$@" --csv) | awk_id
}

while getopts h:p:f:g:t: OPT
do
	case $OPT in
	h) usage ;;
	g) VCLGROUP=$OPTARG ;;
	t) TAGS=$OPTARG ;;
	f) MAIN_VCL=$OPTARG ;;
	p) VCL_PATH=$OPTARG ;;
	*) usage "wrong usage" >&2 ;;
	esac
done

test -z "$VCLGROUP" && usage "-g <VCL Group> is required" >&2
test -z "$TAGS" && usage "-t <tags> is required" >&2
test -z "$MAIN_VCL" && usage "-f <Main VCL> is required" >&2
test -z "$VCL_PATH" && usage "-p <VCL Path> is required" >&2

echo "Reloading VCL Group $VCLGROUP (Main VCL: $MAIN_VCL, VCL path: $VCL_PATH, tags: $TAGS"

DEPLOYMENT="${VCLGROUP}_dc"
VCL_LIST=$(ls $VCL_PATH | grep .*\.vcl)

if ! vcli login; then
	fail "Login failed"
fi

### Add/update files ###

for VCL in $VCL_LIST
do
	VCL_ID=$(vcli_run_quiet file ls -f name="$VCL")
	if [ "$VCL_ID" -eq "0" ] ; then
		echo "Adding File $VCL_PATH/$VCL"
		VCL_ID=$(vcli_run file add "$VCL" "$VCL_PATH/$VCL")
	else
		echo "Updating File $VCL_PATH/$VCL"
		VCL_ID=$(vcli_run file update "$VCL_ID" --file="$VCL_PATH/$VCL")
	fi

	if [ "$VCL_ID" -eq "0" ] ; then
		fail "Error, failed to add/update File $VCL_PATH/$VCL"
	else
		echo "Success: File has id $VCL_ID"
	fi

	if [ "$VCL" = "$MAIN_VCL" ] ; then
		MAIN_VCL_ID="$VCL_ID"
	elif [ -z "$INCLUDES_ID" ] ; then
		INCLUDES_ID="$VCL_ID"
	else
		INCLUDES_ID="$INCLUDES_ID,$VCL_ID"
	fi
done

### Add Tags ###

TAGS_ID=$(vcli_run_quiet tags ls -f name="$TAGS")
if [ "$TAGS_ID" -eq "0" ] ; then
	echo "Adding tags $TAGS"
	TAGS_ID=$(vcli_run tags add "$TAGS")
fi

if [ "$TAGS_ID" -eq "0" ] ; then
	fail "Error, failed to add tags $TAGS"
else
	echo "Success: Tags have id $VCL_ID"
fi

### Add/update Deployment ###

DEPLOYMENT_ID=$(vcli_run_quiet file ls -f name="$DEPLOYMENT")
if [ "$DEPLOYMENT_ID" -eq "0" ] ; then
	echo "Adding Deployment $DEPLOYMENT (--tags: $TAGS_ID)"
	DEPLOYMENT_ID=$(vcli_run deployment add "$DEPLOYMENT" --tags "$TAGS_ID")
else
	echo "Updating Deployment $DEPLOYMENT (id: $DEPLOYMENT_ID, --tags: $TAGS_ID)"
	DEPLOYMENT_ID=$(vcli_run deployment update "$DEPLOYMENT_ID" --tags "$TAGS_ID" --yes)
fi

if [ "$DEPLOYMENT_ID" -eq "0" ] ; then
	fail "Error, failed to add/update deployment $DEPLOYMENT"
else
	echo "Success: Deployment has id $DEPLOYMENT_ID"
fi

### Add/update VCL Group ###

VCLGROUP_ID=$(vcli_run_quiet vclgroup ls -f name="$VCLGROUP")
if [ "$VCLGROUP_ID" -eq "0" ] ; then
	echo "Adding VCL Group $VCLGROUP (--dep: $DEPLOYMENT_ID, --vcl: $MAIN_VCL_ID, --inc: $INCLUDES_ID, --root)"
	VCLGROUP_ID=$(vcli_run vclgroup add "$VCLGROUP" --dep "$DEPLOYMENT_ID" --vcl "$MAIN_VCL_ID" --inc "$INCLUDES_ID" --root)
else
	echo "Updating VCL Group $VCLGROUP (id: $VCLGROUP_ID, --dep: $DEPLOYMENT_ID, --vcl: $MAIN_VCL_ID, --inc: $INCLUDES_ID, --root)"
	VCLGROUP_ID=$(vcli_run vclgroup update "$VCLGROUP_ID" --dep "$DEPLOYMENT_ID" --vcl "$MAIN_VCL_ID" --inc "$INCLUDES_ID" --root --yes)
fi

if [ "$VCLGROUP_ID" -eq "0" ] ; then
	fail "Error, failed to add/update VCL Group"
else
	echo "Success: VCL Group has id $VCLGROUP_ID"
fi

### Compile the VCL Group ###

echo "Compiling VCL Group $VCLGROUP (id: $VCLGROUP_ID)"
VCLGROUP_ID=$(vcli_run vclgroup compile "$VCLGROUP_ID")
if [ "$VCLGROUP_ID" -eq "0" ] ; then
	fail "Error, failed to compile VCL Group"
else
	echo "Success: VCL Group compiled"
fi

### Deploy the VCL Group ##

echo "Deploying VCL Group $VCLGROUP (id: $VCLGROUP_ID)"
VCLGROUP_ID=$(vcli_run vclgroup deploy "$VCLGROUP_ID")
if [ "$VCLGROUP_ID" -eq "0" ] ; then
	fail "Error, failed to deploy VCL Group"
else
	echo "Success: VCL Group deployed"
fi
